# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  parse_block_html: true

future:           true

# Setup
title:            Mayank@UIC
tagline:          Programmer, Full-stack developer, Gamer
description:      Mayank K Rastogi is a tech enthusiast and a passionate programmer who loves solving challenging problems and likes to keep learning awesome stuff!
url:              https://mrasto3.people.uic.edu
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.
assets:
  css:            /assets/css/
  favicons:       /assets/favicons/
  images:         /assets/images/
  js:             /assets/js/

author:
  name:           Mayank K Rastogi
  url:            https://www.mayankrastogi.com
  email:          mrasto3@uic.edu
  facebook:       https://www.facebook.com/MayankKRastogi
  stackoverflow:  https://stackoverflow.com/users/4463881/mayank-k-rastogi
  linkedin:       https://www.linkedin.com/in/mayankkrastogi
  github:         https://github.com/mayankrastogi
  description:    I am a tech enthusiast and a passionate programmer who loves solving challenging problems and likes to keep learning awesome stuff!<br><br>When I'm not coding, I like to bury myself in my PlayStation or relax in the swimming pool!  
  
plugins:
  # - jekyll-feed
  # - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0

github:
  repo:             https://github.com/mayankrastogi/Mayank-UIC